// <auto-generated />
using System;
using Food_Delivery_Platform.DAL.FoodDbContextRepo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Food_Delivery_Platform.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    partial class FoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Food_Delivery_Platform.DAL.Model.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hotel_id")
                        .UseIdentityColumn();

                    b.Property<double>("CashBalance")
                        .HasColumnType("float")
                        .HasColumnName("cash_balance");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("HotelName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hotel_name");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location");

                    b.Property<int>("PinCode")
                        .HasColumnType("int")
                        .HasColumnName("pin_code");

                    b.HasKey("HotelId");

                    b.ToTable("hotels");
                });

            modelBuilder.Entity("Food_Delivery_Platform.DAL.Model.HotelMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("DishName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dish_name");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("hotelmenus");
                });

            modelBuilder.Entity("Food_Delivery_Platform.DAL.Model.HotelStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_time");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<string>("HotelName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hotel_name");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("hotelstatus");
                });

            modelBuilder.Entity("Food_Delivery_Platform.DAL.Model.HotelTransaction", b =>
                {
                    b.Property<int>("TranxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tranx_id")
                        .UseIdentityColumn();

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_name");

                    b.Property<double>("TranxAmt")
                        .HasColumnType("float")
                        .HasColumnName("tranx_amt");

                    b.Property<DateTime>("TranxDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("tranx_date");

                    b.HasKey("TranxId");

                    b.ToTable("hoteltransactions");
                });

            modelBuilder.Entity("Food_Delivery_Platform.DAL.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id")
                        .UseIdentityColumn();

                    b.Property<double>("CashBalance")
                        .HasColumnType("float")
                        .HasColumnName("cash_balance");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("locality");

                    b.Property<int>("PinCode")
                        .HasColumnType("int")
                        .HasColumnName("pin_code");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Food_Delivery_Platform.DAL.Model.UserTranxHistory", b =>
                {
                    b.Property<int>("TranxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tranx_id")
                        .UseIdentityColumn();

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item");

                    b.Property<double>("TranxAmt")
                        .HasColumnType("float")
                        .HasColumnName("tranx_amt");

                    b.Property<DateTime>("TranxDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("tranx_date_time");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TranxId");

                    b.ToTable("usertranxhistory");
                });
#pragma warning restore 612, 618
        }
    }
}
